name: Update README2

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    name: Update Profile README

    steps:
      - uses: action/checkout@v2.3.4
  
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
